

NUMBER_OF_ROWS_IN_SUDOKU_BOARD = 9
NUMBER_OF_COLS_IN_SUDOKU_BOARD = 9
EMPTY_CUBE_VALUE = 0
FIRST_CUBE_IN_AREA = 1
LAST_CUBE_IN_AREA = 1
ROW_INDEX = 0
COL_INDEX = 1
INDEXES_OF_LAST_CUBE_IN_SUDOKU_BOARD = (8, 8)
INDEX_OF_FIRST_COL_IN_SUDOKU_BOARD = 0
INDEX_OF_LAST_COL_IN_SUDOKU_BOARD = 8
INDEX_OF_FIRST_ROW_IN_SUDOKU_BOARD = 0
INDEX_OF_LAST_ROW_IN_SUDOKU_BOARD = 8
SIZE_OF_CUBE = 3
INDEX_OF_LAST_ROW_IN_FIRST_AREA_IN_LINE = 2
INDEX_OF_LAST_COL_IN_FIRST_AREA_IN_LINE = 2
MAX_AMOUNT_OF_CUBES_WITH_THE_SAME_VALUE_IN_AREA = 1
MAX_AMOUNT_OF_CUBES_WITH_THE_SAME_VALUE_IN_ROW = 1
MAX_AMOUNT_OF_CUBES_WITH_THE_SAME_VALUE_IN_COL = 1
MIN_LEGAL_VALUE_OF_SUDOKU_CUBE = 0
MAX_LEGAL_VALUE_OF_SUDOKU_CUBE = 9
MIN_NON_EMPTY_VALUE_OF_SUDOKU_CUBE = 1
CUBE_AREA_INDEXES = 0
CUBE_ROW_INDEX = 1
CUBE_COL_INDEX = 2
THE_DRAWING_RATE_OF_THE_SUDOKU_SOLVING_PROCESS = 190
